A grab bag of improvements (sorry it is all at once): parsing of duration, working_space, contraint clauses; fixed minor bugs in redundancy handling; enabled checking that methods used in annotations are pure; added a -noNotCheckedWarnings, especially for testing; allowed informal predicates where they were causing aborts; implemented some checked on spec_protected; enabled initializers on ghost variables (parsing only); allows non_null on formal parameters if it is present in overridden declarations.

diff --git a/src/escjava/trunk/ESCTools/Escjava/escj b/src/escjava/trunk/ESCTools/Escjava/escj
--- a/src/escjava/trunk/ESCTools/Escjava/escj
+++ b/src/escjava/trunk/ESCTools/Escjava/escj
@@ -8,8 +8,9 @@ if [ -z ${ESCJAVA_ROOT} ]; then
 fi
 
 if [ -z "${ESC_CLASSPATH}" ]; then
-    echo "Error: ESC_CLASSPATH is not set."
-    exit 2
+    ESC_CLASSPATH=${ESCJAVA_ROOT}/classfiles:${ESCJAVA_ROOT}/../Javafe/classfiles
+    ##echo "Error: ESC_CLASSPATH is not set."
+    ##exit 2
 fi
 
 if [ -z "${BOOTCLASSPATH}" ]; then
