Committing a fair amount of editing in support of cleaned up Makefiles, environment variables.  Generated the start of a README and of procedures to generate binary releases.

diff --git a/src/escjava/trunk/ESCTools/Escjava/escj b/src/escjava/trunk/ESCTools/Escjava/escj
--- a/src/escjava/trunk/ESCTools/Escjava/escj
+++ b/src/escjava/trunk/ESCTools/Escjava/escj
@@ -1,65 +1,146 @@
-#!/bin/bash
+#!/bin/tcsh -f
 # Copyright 2001, Compaq Computer Corporation
 # Copyright 2003 University of Nijmegen
+# Copyright 2003 David R. Cok
 
-if [ -z ${ESCJAVA_ROOT} ]; then
-    echo "Error: ESCJAVA_ROOT is not set."
-    exit 2
-fi
+############################################################################
+## Required variables:
+##	ESCTOOLS_ROOT
+##	SIMPLIFY
+##	ESC_CLASSPATH (defaults to the files in the CVS directories)
+##	CLASSPATH (defaults to ".")
 
-if [ -z "${ESC_CLASSPATH}" ]; then
-    ESC_CLASSPATH=${ESCJAVA_ROOT}/classfiles:${ESCJAVA_ROOT}/../Javafe/classfiles
-    ##echo "Error: ESC_CLASSPATH is not set."
-    ##exit 2
-fi
+## Optional variables:
+##	ESCJ_VERBOSE
+##	BOOTCLASSPATH
+##	ESCJ_STDARGS
+##	JAVA
+##	ESC_REMOTE_DEBUG
+##	JAVA_VM_FLAGS
+##	JAVA_VM_DEBUG_FLAGS
+##      ESCJ_SIMPLIFY_DIR
+##      ESCJ_SIMPLIFY_SCRIPT
 
-if [ -z "${BOOTCLASSPATH}" ]; then
-    echo "Error: BOOTCLASSPATH is not set."
-    exit 2
-fi
+############################################################################
 
-if [ -z ${JAVA} ]; then
-  JAVA=java
-fi
+if ( ! $?ESCTOOLS_ROOT ) then
+    set NAME=$PWD/$0
+    if ( -e $NAME ) then
+	set ESCTOOLS_ROOT=$NAME:h:h
+	echo Warning: Guessing ESCTOOLS_ROOT = $ESCTOOLS_ROOT
+    else if ( -e $0 ) then
+	set ESCTOOLS_ROOT=$0:h:h
+	echo Warning: Guessing ESCTOOLS_ROOT = $ESCTOOLS_ROOT
+    endif
+    if ( ! $?ESCTOOLS_ROOT ) then
+	echo "Error: ESCTOOLS_ROOT is not set and guessing was unsuccessful."
+	exit 2
+    endif
+endif
 
-# If no standard arguments are set, set some escjava defaults for now.
-if [ -z "${ESCJ_STDARGS}" ]; then
-    ESCJ_STDARGS="-nowarn Deadlock"
-fi
+setenv ESCJAVA_ROOT ${ESCTOOLS_ROOT}/Escjava
 
-# If a CLASSPATH has been defined, set USERPATH to it, otherwise set
-# USERPATH to '.'.
-if [ -n "${CLASSPATH}" ]; then
-    USERPATH=${CLASSPATH}
+############ Setting ESCJ_SIMPLIFY_DIR, if necessary
+if ( ! $?ESCJ_SIMPLIFY_DIR) then
+setenv ESCJ_SIMPLIFY_DIR ${ESCJAVA_ROOT}/release/master/bin
+endif
+
+############ Setting ESCJ_SIMPLIFY, if necessary
+
+if ( ! $?ESCJ_SIMPLIFY ) then
+    if ( ! $?SIMPLIFY ) then
+	if ( "$OSTYPE" == "linux" ) setenv SIMPLIFY Simplify-1.5.4.linux
+	if ( "$OSTYPE" == "darwin" ) setenv SIMPLIFY Simplify-1.5.4.macosx
+	if ( $?SIMPLIFY ) then
+		echo Warning: Guessing SIMPLIFY = $SIMPLIFY
+	endif
+    endif
+    if ( ! $?SIMPLIFY ) then
+        echo "Error: The SIMPLIFY environment variable must be set to an appropriate value (the name of, not path to, an executable in $ESCJ_SIMPLIFY_DIR )"
+	exit 1
+    endif
+    setenv ESCJ_SIMPLIFY ${ESCJ_SIMPLIFY_DIR}/${SIMPLIFY}
+endif
+    
+## (Optional) If the OS does not supply the class path for Java system files,
+## or you want to override it, then supply a definition for BOOTCLASSPATH
+if ( ! $?BOOTCLASSPATH ) then
+    set JBIN=""
 else
-    USERPATH="."
-fi
+    set JBIN="-bootclasspath ${BOOTCLASSPATH}"
+endif
 
-if ! [ -z ${ESC_REMOTE_DEBUG} ]; then
-  JAVA_VM_DEBUG_FLAGS="-Xdebug -Xnoagent -Djava.compiler=NONE \
--Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y"
-fi
+## (Optional) Supply a definition for JAVA if you want to use a different VM
+if ( ! $?JAVA ) then
+  setenv JAVA java
+endif
 
-if ! [ -z ${ESCJ_VERBOSE} ]; then
-    if [ "${ESCJ_VERBOSE}" == 2 ]; then
+# (Optional) If no standard arguments are set, set some escjava defaults for now.
+if ( ! $?ESCJ_STDARGS ) then
+    setenv ESCJ_STDARGS "-nowarn Deadlock"
+endif
+
+# CLASSPATH is the path on which source files and specs referenced by the files
+# on the command-line will be found.  Include here the classpath for the
+# files on the command-line, source or class files referenced by them, and
+# the paths to any spec files that are needed.  The Java system files are
+# automatically included.  Default is the value of CLASSPATH set in the
+# environment.  If that is not set, the default is the current directory.
+if ( ! $?CLASSPATH ) setenv CLASSPATH .
+
+
+## (Optional) Set this to whatever flags the VM needs (empty by default)
+if ( ! $?JAVA_VM_FLAGS ) setenv JAVA_VM_FLAGS ""
+
+## (Optional) Define ESC_REMOTE_DEBUG to something non-empty to provide 
+## the flags for debugging a run of escjava
+setenv JAVA_VM_DEBUG_FLAGS "-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y"
+if ( $?ESC_REMOTE_DEBUG ) then
+    setenv JAVA_VM_FLAGS "$JAVA_VM_DEBUG_FLAGS $JAVA_VM_FLAGS"
+endif
+
+## (optional) Define ESCJ_VERBOSE to something non-empty to see the 
+## arguments being supplied to the executable
+
+##########################################################################
+
+## This is the path needed to run escjava
+## If it is not set, use the path suitable for working in CVS or in the
+## release
+if ( ! $?ESC_CLASSPATH ) then
+    if ( $?ESCTOOLS_RELEASE ) then
+        setenv ESC_CLASSPATH $ESCTOOLS_RELEASE/esctools.jar
+    else
+        setenv ESC_CLASSPATH ${ESCTOOLS_ROOT}/Escjava/classfiles:${ESCTOOLS_ROOT}/Javafe/classfiles
+    endif
+endif
+
+if ( ! $?ESCJ_SIMPLIFY_SCRIPT ) then
+    if ( $?ESCTOOLS_RELEASE ) then
+        setenv ESCJ_SIMPLIFY_SCRIPT $ESCTOOLS_RELEASE/simplify-script
+    else
+        setenv ESCJ_SIMPLIFY_SCRIPT ${ESCJAVA_ROOT}/simplify
+    endif
+endif
+
+if ( $?ESCJ_VERBOSE ) then
+    if ( "$ESCJ_VERBOSE" == 2 ) then
       echo "=================================================================="
-      set
-    fi
+    endif
     echo "=================================================================="
     echo "Executing:";
     echo "${JAVA} ${JAVA_VM_FLAGS}";
-    echo "  -Dsimplify=${ESCJAVA_ROOT}/simplify";
+    echo "  -Dsimplify=${ESCJ_SIMPLIFY_SCRIPT}";
     echo "  -classpath ${ESC_CLASSPATH}";
     echo "  escjava.Main";
-    echo "  -bootclasspath ${BOOTCLASSPATH}";
-    echo "  -classpath ${USERPATH}";
+    echo "  " ${JBIN} ;
+    echo "  -classpath ${CLASSPATH}";
     echo "  ${ESCJ_STDARGS}";
-    echo "  ${@}";
+    echo "  $*";
+    echo "Also: ESCJ_SIMPLIFY = $ESCJ_SIMPLIFY"
     echo "=================================================================="
-fi
+endif
 
-JAVA_VM_FLAGS=${JAVA_VM_DEBUG_FLAGS}
-
-${JAVA} ${JAVA_VM_FLAGS} -Dsimplify=${ESCJAVA_ROOT}/simplify \
+${JAVA} ${JAVA_VM_FLAGS} -Dsimplify=${ESCJ_SIMPLIFY_SCRIPT} \
     -classpath ${ESC_CLASSPATH} escjava.Main \
-    -bootclasspath ${BOOTCLASSPATH} -classpath ${USERPATH} ${ESCJ_STDARGS} ${@}
+    ${JBIN} -classpath ${CLASSPATH} ${ESCJ_STDARGS} $*
